import { User, Team, Invite } from '@/types';

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    name: 'Engineering',
    description: 'Product development and infrastructure',
    memberIds: ['user-1', 'user-2', 'user-5'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'team-2',
    name: 'Design',
    description: 'Product design and user experience',
    memberIds: ['user-3'],
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'team-3',
    name: 'Marketing',
    description: 'Growth and brand management',
    memberIds: ['user-4'],
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'team-4',
    name: 'Sales',
    description: 'Revenue and customer relationships',
    memberIds: [],
    createdAt: '2024-02-15T10:00:00Z',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    firstName: 'Alex',
    lastName: 'Johnson',
    email: 'alex.johnson@company.com',
    phone: '+1 (555) 123-4567',
    jobTitle: 'Senior Software Engineer',
    department: 'Engineering',
    status: 'active',
    teamIds: ['team-1'],
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: 'user-2',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah.williams@company.com',
    phone: '+1 (555) 234-5678',
    jobTitle: 'Backend Developer',
    department: 'Engineering',
    status: 'active',
    teamIds: ['team-1'],
    createdAt: '2024-01-12T11:00:00Z',
  },
  {
    id: 'user-3',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@company.com',
    jobTitle: 'Product Designer',
    department: 'Design',
    status: 'active',
    teamIds: ['team-2'],
    createdAt: '2024-01-25T14:00:00Z',
  },
  {
    id: 'user-4',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@company.com',
    phone: '+1 (555) 345-6789',
    jobTitle: 'Marketing Manager',
    department: 'Marketing',
    status: 'suspended',
    teamIds: ['team-3'],
    createdAt: '2024-02-05T10:00:00Z',
  },
  {
    id: 'user-5',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@company.com',
    jobTitle: 'DevOps Engineer',
    department: 'Engineering',
    status: 'invited',
    teamIds: ['team-1'],
    createdAt: '2024-03-01T09:00:00Z',
  },
];

export const mockInvites: Invite[] = [
  {
    id: 'invite-1',
    email: 'james.wilson@company.com',
    status: 'pending',
    teamIds: ['team-1'],
    sentAt: '2024-03-01T09:00:00Z',
    expiresAt: '2024-03-08T09:00:00Z',
  },
  {
    id: 'invite-2',
    email: 'lisa.anderson@company.com',
    status: 'pending',
    teamIds: ['team-2', 'team-3'],
    sentAt: '2024-03-05T14:00:00Z',
    expiresAt: '2024-03-12T14:00:00Z',
  },
  {
    id: 'invite-3',
    email: 'robert.taylor@company.com',
    status: 'expired',
    teamIds: ['team-4'],
    sentAt: '2024-02-01T10:00:00Z',
    expiresAt: '2024-02-08T10:00:00Z',
  },
];
